export default Object.freeze({
  BEACH_BAR: [
    "products",
    "products.category",
    "products.components",
    "products.reservationLimits",
    "products.reservationLimits.startTime",
    "products.reservationLimits.endTime",
    "products.reservationLimits.product",
    "features",
    "features.service",
    "location",
    "location.country",
    "location.city",
    "location.region",
    "fee",
    "reviews",
    "reviews.customer",
    "reviews.answer",
    "defaultCurrency",
    "owners",
    "owners.owner",
    "owners.owner.user",
    "entryFees",
    "restaurants",
    "restaurants.foodItems",
  ],
});
