schema: http://localhost:4000/graphql
documents: ./graphql/**/*.graphql
extensions:
  codegen:
    generates:
      ./graphql/generated.ts:
        config:
          avoidOptionals: true
          immutableTypes: true
          maybeValue: T | undefined
          namingConvention:
            - transformUnderscore: false
          reactApolloVersion: 3
          withComponent: false
          withHOC: false
          withHooks: true
          scalars:
            BigInt: number
            Email: string
            Date: string
            DateTime: string
            URL: string
            IPv4: string
            Time: string
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
      ./graphql/schema.graphql:
        plugins:
          - schema-ast
      ./lib/apollo/apollo-helpers.ts:
        plugins:
          - typescript-apollo-client-helpers
