export default Object.freeze({
  NOT_FOUND: "not_found",
  NOT_ACTIVE: "not_active",
  CONFLICT: "conflict",
  INTERNAL_SERVER_ERROR: "internal_server_error",
  SOMETHING_WENT_WRONG: "Something went wrong",
  USER_NOT_FOUND_MESSAGE: "User does not exist",
  INVALID_ARGUMENTS: "invalid_arguments",
  NOT_AUTHENTICATED_CODE: "not_authenticated",
  NOT_AUTHENTICATED_MESSAGE: "You are not authenticated",
  UNAUTHORIZED_CODE: "unauthorized",
  JWT_EXPIRED: "jwt_expired",
  ORIGIN_URI_MISMATCH: "origin_uri_mismatch",
  REDIRECT_URI_MISMATCH: "redirect_uri_mismatch",
  SCOPE_MISMATCH: "scope_mismatch",
  INVALID_PASSWORD_CODE: "invalid_password",
  INVALID_PASSWORD_MESSAGE: "Invalid password",
  GOOGLE_AUTHENTICATED_CODE: "google_authenticated",
  FACEBOOK_AUTHENTICATED_CODE: "facebook_authenticated",
  INSTAGRAM_AUTHENTICATED_CODE: "instagram_authenticated",
  HASHTAG_NOT_AUTHENTICATED_CODE: "hashtag_not_authenticated",
  INVALID_EMAIL_ADDRESS: "Please provide a valid email address",
  EMPTY_VALUES: "Please provide some values",
  BEACH_BAR_DOES_NOT_EXIST: "Specified #beach_bar does not exist",
  USER_DOES_NOT_EXIST: "Specified user does not exist",
});
