import { Add } from "./Add";
import { Arrow } from "./Arrow";
import { Base, PathBase } from "./Base";
import Bookmark from "./Bookmark";
import { Checkmark } from "./Checkmark";
import Chevron from "./Chevron";
import { Close } from "./Close";
import { Edit } from "./Edit";
import { Face } from "./Face";
import Filters from "./Filters";
import { Flame } from "./Flame";
import { Logo } from "./Logo";
import { Share } from "./Share";
import Map from "./Map";
import MapMarker from "./MapMarker";
import { Save } from "./Save";
import { Heart } from "./Heart";
import { Search } from "./Search";
import ShoppingCart from "./ShoppingCart";
import { Star } from "./Star";
import TapBarIndicator from "./TapBarIndicator";
import { Thumb } from "./Thumb";
import { BeachBall } from "./BeachBall";
import { Navigation } from "./Navigation";
import { Beach } from "./Beach";
import { WaterSlides } from "./WaterSlides";
import { Snacks } from "./Snacks";
import { SwimmingPool } from "./SwimmingPool";
import { ParkingSign } from "./ParkingSign";
import { History } from "./History";
import { Chair } from "./Chair";
import { Sunbed } from "./Sunbed";
import { BeachUmbrella } from "./BeachUmbrella";
import { People } from "./People";
import UserAvatar from "./UserAvatar";

type SubComponents = {
  Base: typeof Base;
  PathBase: typeof PathBase;
  Search: typeof Search;
  Map: typeof Map;
  ShoppingCart: typeof ShoppingCart;
  UserAvatar: typeof UserAvatar;
  TapBarIndicator: typeof TapBarIndicator;
  Chevron: typeof Chevron;
  Filters: typeof Filters;
  MapMarker: typeof MapMarker;
  Close: typeof Close;
  Bookmark: typeof Bookmark;
  Logo: typeof Logo;
  Flame: typeof Flame;
  Edit: typeof Edit;
  Save: typeof Save;
  Add: typeof Add;
  Arrow: typeof Arrow;
  Checkmark: typeof Checkmark;
  Thumb: typeof Thumb;
  Face: typeof Face;
  Star: typeof Star;
  Heart: typeof Heart;
  Navigation: typeof Navigation;
  BeachBall: typeof BeachBall;
  WaterSlides: typeof WaterSlides;
  Snacks: typeof Snacks;
  ParkingSign: typeof ParkingSign;
  SwimmingPool: typeof SwimmingPool;
  Beach: typeof Beach;
  History: typeof History;
  Share: typeof Share;
  People: typeof People;
  Chair: typeof Chair;
  Sunbed: typeof Sunbed;
  BeachUmbrella: typeof BeachUmbrella;
};

const Icons: React.FC & SubComponents = () => {
  return <></>;
};

Icons.displayName = "Icons";

Icons.Search = Search;
Icons.Base = Base;
Icons.PathBase = PathBase;
Icons.Map = Map;
Icons.ShoppingCart = ShoppingCart;
Icons.UserAvatar = UserAvatar;
Icons.TapBarIndicator = TapBarIndicator;
Icons.Chevron = Chevron;
Icons.Filters = Filters;
Icons.MapMarker = MapMarker;
Icons.Close = Close;
Icons.Bookmark = Bookmark;
Icons.Logo = Logo;
Icons.Flame = Flame;
Icons.Edit = Edit;
Icons.Save = Save;
Icons.Add = Add;
Icons.Arrow = Arrow;
Icons.Checkmark = Checkmark;
Icons.Thumb = Thumb;
Icons.Face = Face;
Icons.Star = Star;
Icons.Heart = Heart;
Icons.Navigation = Navigation;
Icons.BeachBall = BeachBall;
Icons.WaterSlides = WaterSlides;
Icons.Snacks = Snacks;
Icons.ParkingSign = ParkingSign;
Icons.SwimmingPool = SwimmingPool;
Icons.Beach = Beach;
Icons.History = History;
Icons.Share = Share;
Icons.People = People;
Icons.Chair = Chair;
Icons.Sunbed = Sunbed;
Icons.BeachUmbrella = BeachUmbrella;

export default Icons;

export { TapBarIndicatorIconPath } from "./TapBarIndicator";
